# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration.ui'
#
# Created: Sun May  1 17:50:45 2011
#      by: pyside-uic 0.2.8 running on PySide 1.0.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_settings_dialog(object):
    def setupUi(self, settings_dialog):
        settings_dialog.setObjectName("settings_dialog")
        settings_dialog.setWindowModality(QtCore.Qt.WindowModal)
        settings_dialog.resize(400, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settings_dialog.sizePolicy().hasHeightForWidth())
        settings_dialog.setSizePolicy(sizePolicy)
        settings_dialog.setMinimumSize(QtCore.QSize(400, 600))
        settings_dialog.setMaximumSize(QtCore.QSize(15536, 15536))
        settings_dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        settings_dialog.setWindowFilePath("")
        self.verticalLayout_5 = QtGui.QVBoxLayout(settings_dialog)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtGui.QTabWidget(settings_dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(398, 567))
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tray_icon = QtGui.QCheckBox(self.groupBox)
        self.tray_icon.setChecked(True)
        self.tray_icon.setObjectName("tray_icon")
        self.verticalLayout.addWidget(self.tray_icon)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.cover_size = QtGui.QSpinBox(self.groupBox)
        self.cover_size.setMinimum(24)
        self.cover_size.setMaximum(480)
        self.cover_size.setSingleStep(10)
        self.cover_size.setProperty("value", 200)
        self.cover_size.setObjectName("cover_size")
        self.horizontalLayout_4.addWidget(self.cover_size)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.remember_current = QtGui.QCheckBox(self.groupBox_3)
        self.remember_current.setObjectName("remember_current")
        self.verticalLayout_2.addWidget(self.remember_current)
        self.context_browser_change = QtGui.QCheckBox(self.groupBox_3)
        self.context_browser_change.setObjectName("context_browser_change")
        self.verticalLayout_2.addWidget(self.context_browser_change)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.collection_view = QtGui.QTreeView(self.groupBox_4)
        self.collection_view.setMinimumSize(QtCore.QSize(200, 0))
        self.collection_view.setIndentation(20)
        self.collection_view.setExpandsOnDoubleClick(True)
        self.collection_view.setObjectName("collection_view")
        self.gridLayout_2.addWidget(self.collection_view, 1, 0, 1, 1)
        self.scan_recursively = QtGui.QCheckBox(self.groupBox_4)
        self.scan_recursively.setChecked(True)
        self.scan_recursively.setObjectName("scan_recursively")
        self.gridLayout_2.addWidget(self.scan_recursively, 2, 0, 1, 1)
        self.watch_folders = QtGui.QCheckBox(self.groupBox_4)
        self.watch_folders.setChecked(True)
        self.watch_folders.setObjectName("watch_folders")
        self.gridLayout_2.addWidget(self.watch_folders, 3, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.database_type = QtGui.QComboBox(self.groupBox_5)
        self.database_type.setMinimumSize(QtCore.QSize(80, 0))
        self.database_type.setMaxVisibleItems(5)
        self.database_type.setMaxCount(5)
        self.database_type.setModelColumn(0)
        self.database_type.setObjectName("database_type")
        self.database_type.addItem("")
        self.horizontalLayout_6.addWidget(self.database_type)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.mysql_config = QtGui.QGroupBox(self.groupBox_5)
        self.mysql_config.setEnabled(False)
        self.mysql_config.setObjectName("mysql_config")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.mysql_config)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtGui.QLabel(self.mysql_config)
        self.label_5.setMinimumSize(QtCore.QSize(65, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.mysql_host = QtGui.QLineEdit(self.mysql_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mysql_host.sizePolicy().hasHeightForWidth())
        self.mysql_host.setSizePolicy(sizePolicy)
        self.mysql_host.setMinimumSize(QtCore.QSize(150, 0))
        self.mysql_host.setMaximumSize(QtCore.QSize(65535, 65535))
        self.mysql_host.setObjectName("mysql_host")
        self.horizontalLayout_7.addWidget(self.mysql_host)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_7 = QtGui.QLabel(self.mysql_config)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.mysql_port = QtGui.QSpinBox(self.mysql_config)
        self.mysql_port.setMinimum(3306)
        self.mysql_port.setMaximum(65535)
        self.mysql_port.setObjectName("mysql_port")
        self.horizontalLayout_7.addWidget(self.mysql_port)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtGui.QLabel(self.mysql_config)
        self.label_6.setMinimumSize(QtCore.QSize(65, 0))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.mysql_dbname = QtGui.QLineEdit(self.mysql_config)
        self.mysql_dbname.setMinimumSize(QtCore.QSize(150, 0))
        self.mysql_dbname.setMaximumSize(QtCore.QSize(65535, 65535))
        self.mysql_dbname.setObjectName("mysql_dbname")
        self.horizontalLayout_8.addWidget(self.mysql_dbname)
        spacerItem2 = QtGui.QSpacerItem(111, 23, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.line = QtGui.QFrame(self.mysql_config)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtGui.QLabel(self.mysql_config)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.mysql_user = QtGui.QLineEdit(self.mysql_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mysql_user.sizePolicy().hasHeightForWidth())
        self.mysql_user.setSizePolicy(sizePolicy)
        self.mysql_user.setMaximumSize(QtCore.QSize(65535, 16777215))
        self.mysql_user.setObjectName("mysql_user")
        self.horizontalLayout_9.addWidget(self.mysql_user)
        self.label_9 = QtGui.QLabel(self.mysql_config)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.mysql_password = QtGui.QLineEdit(self.mysql_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mysql_password.sizePolicy().hasHeightForWidth())
        self.mysql_password.setSizePolicy(sizePolicy)
        self.mysql_password.setMaximumSize(QtCore.QSize(65535, 16777215))
        self.mysql_password.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.mysql_password.setObjectName("mysql_password")
        self.horizontalLayout_9.addWidget(self.mysql_password)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.addWidget(self.mysql_config)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.buttonBox = QtGui.QDialogButtonBox(settings_dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(settings_dialog)
        self.tabWidget.setCurrentIndex(1)
        self.database_type.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settings_dialog)

    def retranslateUi(self, settings_dialog):
        settings_dialog.setWindowTitle(QtGui.QApplication.translate("settings_dialog", "Configure - Gereqi", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("settings_dialog", "General Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tray_icon.setText(QtGui.QApplication.translate("settings_dialog", "Show tray icon", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("settings_dialog", "Default size for cover previews: ", None, QtGui.QApplication.UnicodeUTF8))
        self.cover_size.setSuffix(QtGui.QApplication.translate("settings_dialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("settings_dialog", "Playlist Window Options", None, QtGui.QApplication.UnicodeUTF8))
        self.remember_current.setText(QtGui.QApplication.translate("settings_dialog", "Remember current playlist on exit", None, QtGui.QApplication.UnicodeUTF8))
        self.context_browser_change.setText(QtGui.QApplication.translate("settings_dialog", "Switch to context browser on track change", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("settings_dialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("settings_dialog", "Collection Folders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("settings_dialog", "These folders will be scanned for media to make up your collection:", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_recursively.setText(QtGui.QApplication.translate("settings_dialog", "Scan folders recursively", None, QtGui.QApplication.UnicodeUTF8))
        self.watch_folders.setText(QtGui.QApplication.translate("settings_dialog", "Watch folders for change", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("settings_dialog", "Collection Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("settings_dialog", "Database: ", None, QtGui.QApplication.UnicodeUTF8))
        self.database_type.setItemText(0, QtGui.QApplication.translate("settings_dialog", "SQLITE", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_config.setTitle(QtGui.QApplication.translate("settings_dialog", "MySql Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("settings_dialog", "Hostname:", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_host.setText(QtGui.QApplication.translate("settings_dialog", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("settings_dialog", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("settings_dialog", "Database:", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_dbname.setText(QtGui.QApplication.translate("settings_dialog", "gereqi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("settings_dialog", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("settings_dialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("settings_dialog", "Collection", None, QtGui.QApplication.UnicodeUTF8))

