# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration.ui'
#
# Created: Fri Apr 27 12:57:48 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_settings_dialog(object):
    def setupUi(self, settings_dialog):
        settings_dialog.setObjectName(_fromUtf8("settings_dialog"))
        settings_dialog.setWindowModality(QtCore.Qt.WindowModal)
        settings_dialog.resize(400, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settings_dialog.sizePolicy().hasHeightForWidth())
        settings_dialog.setSizePolicy(sizePolicy)
        settings_dialog.setMinimumSize(QtCore.QSize(400, 600))
        settings_dialog.setMaximumSize(QtCore.QSize(15536, 15536))
        settings_dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        settings_dialog.setWindowFilePath(_fromUtf8(""))
        self.verticalLayout_5 = QtGui.QVBoxLayout(settings_dialog)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_5.setMargin(1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(settings_dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(398, 567))
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setMargin(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tray_icon = QtGui.QCheckBox(self.groupBox)
        self.tray_icon.setChecked(True)
        self.tray_icon.setObjectName(_fromUtf8("tray_icon"))
        self.verticalLayout.addWidget(self.tray_icon)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.cover_size = QtGui.QSpinBox(self.groupBox)
        self.cover_size.setMinimum(24)
        self.cover_size.setMaximum(480)
        self.cover_size.setSingleStep(10)
        self.cover_size.setProperty("value", 200)
        self.cover_size.setObjectName(_fromUtf8("cover_size"))
        self.horizontalLayout_4.addWidget(self.cover_size)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.remember_current = QtGui.QCheckBox(self.groupBox_3)
        self.remember_current.setObjectName(_fromUtf8("remember_current"))
        self.verticalLayout_2.addWidget(self.remember_current)
        self.context_browser_change = QtGui.QCheckBox(self.groupBox_3)
        self.context_browser_change.setObjectName(_fromUtf8("context_browser_change"))
        self.verticalLayout_2.addWidget(self.context_browser_change)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setMargin(2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.collection_view = QtGui.QTreeView(self.groupBox_4)
        self.collection_view.setMinimumSize(QtCore.QSize(200, 0))
        self.collection_view.setIndentation(20)
        self.collection_view.setExpandsOnDoubleClick(True)
        self.collection_view.setObjectName(_fromUtf8("collection_view"))
        self.gridLayout_2.addWidget(self.collection_view, 1, 0, 1, 1)
        self.scan_recursively = QtGui.QCheckBox(self.groupBox_4)
        self.scan_recursively.setChecked(True)
        self.scan_recursively.setObjectName(_fromUtf8("scan_recursively"))
        self.gridLayout_2.addWidget(self.scan_recursively, 2, 0, 1, 1)
        self.watch_folders = QtGui.QCheckBox(self.groupBox_4)
        self.watch_folders.setChecked(True)
        self.watch_folders.setObjectName(_fromUtf8("watch_folders"))
        self.gridLayout_2.addWidget(self.watch_folders, 3, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(settings_dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(settings_dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settings_dialog)

    def retranslateUi(self, settings_dialog):
        settings_dialog.setWindowTitle(QtGui.QApplication.translate("settings_dialog", "Configure - Gereqi", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("settings_dialog", "General Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tray_icon.setText(QtGui.QApplication.translate("settings_dialog", "Show tray icon", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("settings_dialog", "Default size for cover previews: ", None, QtGui.QApplication.UnicodeUTF8))
        self.cover_size.setSuffix(QtGui.QApplication.translate("settings_dialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("settings_dialog", "Playlist Window Options", None, QtGui.QApplication.UnicodeUTF8))
        self.remember_current.setText(QtGui.QApplication.translate("settings_dialog", "Remember current playlist on exit", None, QtGui.QApplication.UnicodeUTF8))
        self.context_browser_change.setText(QtGui.QApplication.translate("settings_dialog", "Switch to context browser on track change", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("settings_dialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("settings_dialog", "Collection Folders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("settings_dialog", "These folders will be scanned for media to make up your collection:", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_recursively.setText(QtGui.QApplication.translate("settings_dialog", "Scan folders recursively", None, QtGui.QApplication.UnicodeUTF8))
        self.watch_folders.setText(QtGui.QApplication.translate("settings_dialog", "Watch folders for change", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("settings_dialog", "Collection", None, QtGui.QApplication.UnicodeUTF8))

