# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Thu Jan 20 23:03:07 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(799, 538)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.vertical_tabs = QtGui.QTabWidget(self.splitter)
        self.vertical_tabs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertical_tabs.sizePolicy().hasHeightForWidth())
        self.vertical_tabs.setSizePolicy(sizePolicy)
        self.vertical_tabs.setMinimumSize(QtCore.QSize(280, 0))
        self.vertical_tabs.setMaximumSize(QtCore.QSize(600, 16777215))
        self.vertical_tabs.setTabPosition(QtGui.QTabWidget.West)
        self.vertical_tabs.setDocumentMode(True)
        self.vertical_tabs.setObjectName(_fromUtf8("vertical_tabs"))
        self.contentTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentTab.sizePolicy().hasHeightForWidth())
        self.contentTab.setSizePolicy(sizePolicy)
        self.contentTab.setObjectName(_fromUtf8("contentTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.contentTab)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontal_tabs = QtGui.QTabWidget(self.contentTab)
        self.horizontal_tabs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontal_tabs.sizePolicy().hasHeightForWidth())
        self.horizontal_tabs.setSizePolicy(sizePolicy)
        self.horizontal_tabs.setMinimumSize(QtCore.QSize(250, 0))
        self.horizontal_tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.horizontal_tabs.setUsesScrollButtons(False)
        self.horizontal_tabs.setDocumentMode(True)
        self.horizontal_tabs.setTabsClosable(False)
        self.horizontal_tabs.setMovable(False)
        self.horizontal_tabs.setObjectName(_fromUtf8("horizontal_tabs"))
        self.musicTab = QtGui.QWidget()
        self.musicTab.setObjectName(_fromUtf8("musicTab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.musicTab)
        self.gridLayout_12.setMargin(2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.info_view = QtWebKit.QWebView(self.musicTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_view.sizePolicy().hasHeightForWidth())
        self.info_view.setSizePolicy(sizePolicy)
        self.info_view.setAcceptDrops(False)
        self.info_view.setToolTip(_fromUtf8(""))
        self.info_view.setWhatsThis(_fromUtf8(""))
        self.info_view.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.info_view.setObjectName(_fromUtf8("info_view"))
        self.gridLayout_12.addWidget(self.info_view, 0, 0, 1, 1)
        self.horizontal_tabs.addTab(self.musicTab, _fromUtf8(""))
        self.wikipediaTab = QtGui.QWidget()
        self.wikipediaTab.setObjectName(_fromUtf8("wikipediaTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wikipediaTab)
        self.gridLayout_4.setMargin(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.wiki_view = QtWebKit.QWebView(self.wikipediaTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wiki_view.sizePolicy().hasHeightForWidth())
        self.wiki_view.setSizePolicy(sizePolicy)
        self.wiki_view.setAutoFillBackground(True)
        self.wiki_view.setStyleSheet(_fromUtf8(""))
        self.wiki_view.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.wiki_view.setZoomFactor(1.0)
        self.wiki_view.setObjectName(_fromUtf8("wiki_view"))
        self.gridLayout_4.addWidget(self.wiki_view, 0, 0, 1, 1)
        self.horizontal_tabs.addTab(self.wikipediaTab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.horizontal_tabs, 0, 1, 1, 1)
        self.vertical_tabs.addTab(self.contentTab, _fromUtf8(""))
        self.collectionTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectionTab.sizePolicy().hasHeightForWidth())
        self.collectionTab.setSizePolicy(sizePolicy)
        self.collectionTab.setObjectName(_fromUtf8("collectionTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.collectionTab)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.clear_collect_bttn = QtGui.QToolButton(self.collectionTab)
        self.clear_collect_bttn.setIconSize(QtCore.QSize(24, 24))
        self.clear_collect_bttn.setAutoRaise(True)
        self.clear_collect_bttn.setObjectName(_fromUtf8("clear_collect_bttn"))
        self.horizontalLayout.addWidget(self.clear_collect_bttn)
        self.search_collect_edit = QtGui.QLineEdit(self.collectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_collect_edit.sizePolicy().hasHeightForWidth())
        self.search_collect_edit.setSizePolicy(sizePolicy)
        self.search_collect_edit.setObjectName(_fromUtf8("search_collect_edit"))
        self.horizontalLayout.addWidget(self.search_collect_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.collect_time_box = QtGui.QComboBox(self.collectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collect_time_box.sizePolicy().hasHeightForWidth())
        self.collect_time_box.setSizePolicy(sizePolicy)
        self.collect_time_box.setMaxVisibleItems(6)
        self.collect_time_box.setMaxCount(6)
        self.collect_time_box.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.collect_time_box.setFrame(True)
        self.collect_time_box.setObjectName(_fromUtf8("collect_time_box"))
        self.collect_time_box.addItem(_fromUtf8(""))
        self.collect_time_box.addItem(_fromUtf8(""))
        self.collect_time_box.addItem(_fromUtf8(""))
        self.collect_time_box.addItem(_fromUtf8(""))
        self.collect_time_box.addItem(_fromUtf8(""))
        self.collect_time_box.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.collect_time_box)
        self.collect_tree = QtGui.QTreeWidget(self.collectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collect_tree.sizePolicy().hasHeightForWidth())
        self.collect_tree.setSizePolicy(sizePolicy)
        self.collect_tree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.collect_tree.setProperty(_fromUtf8("showDropIndicator"), False)
        self.collect_tree.setAlternatingRowColors(True)
        self.collect_tree.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.collect_tree.setIndentation(15)
        self.collect_tree.setRootIsDecorated(True)
        self.collect_tree.setUniformRowHeights(True)
        self.collect_tree.setAnimated(True)
        self.collect_tree.setExpandsOnDoubleClick(False)
        self.collect_tree.setObjectName(_fromUtf8("collect_tree"))
        self.verticalLayout_2.addWidget(self.collect_tree)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.vertical_tabs.addTab(self.collectionTab, _fromUtf8(""))
        self.playlistsTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlistsTab.sizePolicy().hasHeightForWidth())
        self.playlistsTab.setSizePolicy(sizePolicy)
        self.playlistsTab.setObjectName(_fromUtf8("playlistsTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.playlistsTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.line_2 = QtGui.QFrame(self.playlistsTab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_5.addWidget(self.line_2)
        self.rename_playlist_bttn = QtGui.QToolButton(self.playlistsTab)
        self.rename_playlist_bttn.setIconSize(QtCore.QSize(24, 24))
        self.rename_playlist_bttn.setAutoRaise(True)
        self.rename_playlist_bttn.setObjectName(_fromUtf8("rename_playlist_bttn"))
        self.horizontalLayout_5.addWidget(self.rename_playlist_bttn)
        self.delete_playlist_bttn = QtGui.QToolButton(self.playlistsTab)
        self.delete_playlist_bttn.setIconSize(QtCore.QSize(24, 24))
        self.delete_playlist_bttn.setAutoRaise(True)
        self.delete_playlist_bttn.setObjectName(_fromUtf8("delete_playlist_bttn"))
        self.horizontalLayout_5.addWidget(self.delete_playlist_bttn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.playlist_tree = QtGui.QTreeWidget(self.playlistsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlist_tree.sizePolicy().hasHeightForWidth())
        self.playlist_tree.setSizePolicy(sizePolicy)
        self.playlist_tree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.playlist_tree.setProperty(_fromUtf8("showDropIndicator"), False)
        self.playlist_tree.setObjectName(_fromUtf8("playlist_tree"))
        self.verticalLayout_5.addWidget(self.playlist_tree)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.vertical_tabs.addTab(self.playlistsTab, _fromUtf8(""))
        self.filesTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesTab.sizePolicy().hasHeightForWidth())
        self.filesTab.setSizePolicy(sizePolicy)
        self.filesTab.setObjectName(_fromUtf8("filesTab"))
        self.gridLayout_13 = QtGui.QGridLayout(self.filesTab)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.filesystem_tree = QtGui.QTreeView(self.filesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesystem_tree.sizePolicy().hasHeightForWidth())
        self.filesystem_tree.setSizePolicy(sizePolicy)
        self.filesystem_tree.setIndentation(15)
        self.filesystem_tree.setExpandsOnDoubleClick(False)
        self.filesystem_tree.setObjectName(_fromUtf8("filesystem_tree"))
        self.gridLayout_13.addWidget(self.filesystem_tree, 0, 0, 1, 1)
        self.vertical_tabs.addTab(self.filesTab, _fromUtf8(""))
        self.devTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devTab.sizePolicy().hasHeightForWidth())
        self.devTab.setSizePolicy(sizePolicy)
        self.devTab.setObjectName(_fromUtf8("devTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.devTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.connect_dev = QtGui.QPushButton(self.devTab)
        self.connect_dev.setObjectName(_fromUtf8("connect_dev"))
        self.horizontalLayout_6.addWidget(self.connect_dev)
        self.disconnect_dev = QtGui.QPushButton(self.devTab)
        self.disconnect_dev.setEnabled(False)
        self.disconnect_dev.setObjectName(_fromUtf8("disconnect_dev"))
        self.horizontalLayout_6.addWidget(self.disconnect_dev)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.devices_box = QtGui.QComboBox(self.devTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devices_box.sizePolicy().hasHeightForWidth())
        self.devices_box.setSizePolicy(sizePolicy)
        self.devices_box.setObjectName(_fromUtf8("devices_box"))
        self.gridLayout_5.addWidget(self.devices_box, 1, 0, 1, 1)
        self.device_view = QtGui.QTreeWidget(self.devTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.device_view.sizePolicy().hasHeightForWidth())
        self.device_view.setSizePolicy(sizePolicy)
        self.device_view.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.device_view.setAlternatingRowColors(True)
        self.device_view.setRootIsDecorated(True)
        self.device_view.setUniformRowHeights(True)
        self.device_view.setItemsExpandable(True)
        self.device_view.setAnimated(True)
        self.device_view.setHeaderHidden(True)
        self.device_view.setExpandsOnDoubleClick(False)
        self.device_view.setObjectName(_fromUtf8("device_view"))
        self.device_view.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_5.addWidget(self.device_view, 2, 0, 1, 1)
        self.vertical_tabs.addTab(self.devTab, _fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.clear_trktbl_bttn = QtGui.QToolButton(self.layoutWidget)
        self.clear_trktbl_bttn.setEnabled(False)
        self.clear_trktbl_bttn.setIconSize(QtCore.QSize(24, 24))
        self.clear_trktbl_bttn.setAutoRaise(True)
        self.clear_trktbl_bttn.setObjectName(_fromUtf8("clear_trktbl_bttn"))
        self.horizontalLayout_4.addWidget(self.clear_trktbl_bttn)
        self.save_trktbl_bttn = QtGui.QToolButton(self.layoutWidget)
        self.save_trktbl_bttn.setIconSize(QtCore.QSize(24, 24))
        self.save_trktbl_bttn.setAutoRaise(True)
        self.save_trktbl_bttn.setObjectName(_fromUtf8("save_trktbl_bttn"))
        self.horizontalLayout_4.addWidget(self.save_trktbl_bttn)
        self.prev_trktbl_bttn = QtGui.QToolButton(self.layoutWidget)
        self.prev_trktbl_bttn.setEnabled(False)
        self.prev_trktbl_bttn.setIconSize(QtCore.QSize(24, 24))
        self.prev_trktbl_bttn.setAutoRaise(True)
        self.prev_trktbl_bttn.setObjectName(_fromUtf8("prev_trktbl_bttn"))
        self.horizontalLayout_4.addWidget(self.prev_trktbl_bttn)
        self.next_trktbl_bttn = QtGui.QToolButton(self.layoutWidget)
        self.next_trktbl_bttn.setEnabled(False)
        self.next_trktbl_bttn.setIconSize(QtCore.QSize(24, 24))
        self.next_trktbl_bttn.setAutoRaise(True)
        self.next_trktbl_bttn.setObjectName(_fromUtf8("next_trktbl_bttn"))
        self.horizontalLayout_4.addWidget(self.next_trktbl_bttn)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.clear_search_bttn = QtGui.QToolButton(self.layoutWidget)
        self.clear_search_bttn.setIconSize(QtCore.QSize(24, 24))
        self.clear_search_bttn.setAutoRaise(True)
        self.clear_search_bttn.setObjectName(_fromUtf8("clear_search_bttn"))
        self.horizontalLayout_4.addWidget(self.clear_search_bttn)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.search_trktbl_edit = QtGui.QLineEdit(self.layoutWidget)
        self.search_trktbl_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.search_trktbl_edit.setObjectName(_fromUtf8("search_trktbl_edit"))
        self.horizontalLayout_4.addWidget(self.search_trktbl_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.track_tbl = QtGui.QTableWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.track_tbl.sizePolicy().hasHeightForWidth())
        self.track_tbl.setSizePolicy(sizePolicy)
        self.track_tbl.setMinimumSize(QtCore.QSize(400, 0))
        self.track_tbl.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.track_tbl.setProperty(_fromUtf8("showDropIndicator"), False)
        self.track_tbl.setDragEnabled(True)
        self.track_tbl.setDragDropOverwriteMode(False)
        self.track_tbl.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.track_tbl.setAlternatingRowColors(True)
        self.track_tbl.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.track_tbl.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.track_tbl.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.track_tbl.setShowGrid(False)
        self.track_tbl.setGridStyle(QtCore.Qt.DashLine)
        self.track_tbl.setWordWrap(False)
        self.track_tbl.setCornerButtonEnabled(True)
        self.track_tbl.setObjectName(_fromUtf8("track_tbl"))
        self.track_tbl.setColumnCount(0)
        self.track_tbl.setRowCount(0)
        self.track_tbl.horizontalHeader().setVisible(True)
        self.track_tbl.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.track_tbl)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.prev_bttn = QtGui.QToolButton(self.layoutWidget)
        self.prev_bttn.setText(_fromUtf8(""))
        self.prev_bttn.setIconSize(QtCore.QSize(24, 24))
        self.prev_bttn.setAutoRaise(True)
        self.prev_bttn.setObjectName(_fromUtf8("prev_bttn"))
        self.horizontalLayout_3.addWidget(self.prev_bttn)
        self.play_bttn = QtGui.QToolButton(self.layoutWidget)
        self.play_bttn.setText(_fromUtf8(""))
        self.play_bttn.setIconSize(QtCore.QSize(24, 24))
        self.play_bttn.setCheckable(True)
        self.play_bttn.setAutoRaise(True)
        self.play_bttn.setObjectName(_fromUtf8("play_bttn"))
        self.horizontalLayout_3.addWidget(self.play_bttn)
        self.stop_bttn = QtGui.QToolButton(self.layoutWidget)
        self.stop_bttn.setEnabled(False)
        self.stop_bttn.setText(_fromUtf8(""))
        self.stop_bttn.setIconSize(QtCore.QSize(24, 24))
        self.stop_bttn.setAutoRaise(True)
        self.stop_bttn.setObjectName(_fromUtf8("stop_bttn"))
        self.horizontalLayout_3.addWidget(self.stop_bttn)
        self.next_bttn = QtGui.QToolButton(self.layoutWidget)
        self.next_bttn.setText(_fromUtf8(""))
        self.next_bttn.setIconSize(QtCore.QSize(24, 24))
        self.next_bttn.setAutoRaise(True)
        self.next_bttn.setObjectName(_fromUtf8("next_bttn"))
        self.horizontalLayout_3.addWidget(self.next_bttn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.mute_bttn = QtGui.QToolButton(self.layoutWidget)
        self.mute_bttn.setText(_fromUtf8(""))
        self.mute_bttn.setIconSize(QtCore.QSize(24, 24))
        self.mute_bttn.setCheckable(True)
        self.mute_bttn.setAutoRaise(True)
        self.mute_bttn.setObjectName(_fromUtf8("mute_bttn"))
        self.horizontalLayout_3.addWidget(self.mute_bttn)
        self.volume_sldr = QtGui.QSlider(self.layoutWidget)
        self.volume_sldr.setMaximumSize(QtCore.QSize(200, 200))
        self.volume_sldr.setMaximum(100)
        self.volume_sldr.setProperty(_fromUtf8("value"), 100)
        self.volume_sldr.setOrientation(QtCore.Qt.Horizontal)
        self.volume_sldr.setInvertedAppearance(False)
        self.volume_sldr.setInvertedControls(False)
        self.volume_sldr.setTickPosition(QtGui.QSlider.NoTicks)
        self.volume_sldr.setObjectName(_fromUtf8("volume_sldr"))
        self.horizontalLayout_3.addWidget(self.volume_sldr)
        self.volume_lbl = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume_lbl.sizePolicy().hasHeightForWidth())
        self.volume_lbl.setSizePolicy(sizePolicy)
        self.volume_lbl.setMinimumSize(QtCore.QSize(24, 0))
        self.volume_lbl.setObjectName(_fromUtf8("volume_lbl"))
        self.horizontalLayout_3.addWidget(self.volume_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.progress_sldr = QtGui.QSlider(self.layoutWidget)
        self.progress_sldr.setMaximum(0)
        self.progress_sldr.setOrientation(QtCore.Qt.Horizontal)
        self.progress_sldr.setObjectName(_fromUtf8("progress_sldr"))
        self.horizontalLayout_2.addWidget(self.progress_sldr)
        self.progress_lbl = QtGui.QLabel(self.layoutWidget)
        self.progress_lbl.setObjectName(_fromUtf8("progress_lbl"))
        self.horizontalLayout_2.addWidget(self.progress_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 799, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuActions = QtGui.QMenu(self.menuBar)
        self.menuActions.setObjectName(_fromUtf8("menuActions"))
        self.menuPlaylist = QtGui.QMenu(self.menuBar)
        self.menuPlaylist.setObjectName(_fromUtf8("menuPlaylist"))
        self.menuSettings = QtGui.QMenu(self.menuBar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionConfigure = QtGui.QAction(MainWindow)
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionRescan_Collection = QtGui.QAction(MainWindow)
        self.actionRescan_Collection.setObjectName(_fromUtf8("actionRescan_Collection"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.play_media_actn = QtGui.QAction(MainWindow)
        self.play_media_actn.setObjectName(_fromUtf8("play_media_actn"))
        self.minimise_tray_actn = QtGui.QAction(MainWindow)
        self.minimise_tray_actn.setCheckable(True)
        self.minimise_tray_actn.setChecked(True)
        self.minimise_tray_actn.setObjectName(_fromUtf8("minimise_tray_actn"))
        self.actionUpdate_Collection = QtGui.QAction(MainWindow)
        self.actionUpdate_Collection.setObjectName(_fromUtf8("actionUpdate_Collection"))
        self.actionAbout_Gereqi = QtGui.QAction(MainWindow)
        self.actionAbout_Gereqi.setObjectName(_fromUtf8("actionAbout_Gereqi"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionRptOff = QtGui.QAction(MainWindow)
        self.actionRptOff.setCheckable(True)
        self.actionRptOff.setChecked(True)
        self.actionRptOff.setObjectName(_fromUtf8("actionRptOff"))
        self.actionRptTrack = QtGui.QAction(MainWindow)
        self.actionRptTrack.setCheckable(True)
        self.actionRptTrack.setObjectName(_fromUtf8("actionRptTrack"))
        self.actionRptAlbum = QtGui.QAction(MainWindow)
        self.actionRptAlbum.setCheckable(True)
        self.actionRptAlbum.setObjectName(_fromUtf8("actionRptAlbum"))
        self.actionRptPlaylist = QtGui.QAction(MainWindow)
        self.actionRptPlaylist.setCheckable(True)
        self.actionRptPlaylist.setObjectName(_fromUtf8("actionRptPlaylist"))
        self.actionRndOff = QtGui.QAction(MainWindow)
        self.actionRndOff.setCheckable(True)
        self.actionRndOff.setChecked(True)
        self.actionRndOff.setObjectName(_fromUtf8("actionRndOff"))
        self.actionRndTrack = QtGui.QAction(MainWindow)
        self.actionRndTrack.setCheckable(True)
        self.actionRndTrack.setObjectName(_fromUtf8("actionRndTrack"))
        self.actionRndAlbum = QtGui.QAction(MainWindow)
        self.actionRndAlbum.setCheckable(True)
        self.actionRndAlbum.setObjectName(_fromUtf8("actionRndAlbum"))
        self.actionFavor = QtGui.QAction(MainWindow)
        self.actionFavor.setObjectName(_fromUtf8("actionFavor"))
        self.play_cd_actn = QtGui.QAction(MainWindow)
        self.play_cd_actn.setObjectName(_fromUtf8("play_cd_actn"))
        self.prev_track_actn = QtGui.QAction(MainWindow)
        self.prev_track_actn.setObjectName(_fromUtf8("prev_track_actn"))
        self.play_actn = QtGui.QAction(MainWindow)
        self.play_actn.setCheckable(True)
        self.play_actn.setObjectName(_fromUtf8("play_actn"))
        self.stop_actn = QtGui.QAction(MainWindow)
        self.stop_actn.setObjectName(_fromUtf8("stop_actn"))
        self.actionNext_Track = QtGui.QAction(MainWindow)
        self.actionNext_Track.setObjectName(_fromUtf8("actionNext_Track"))
        self.actionEqualiser = QtGui.QAction(MainWindow)
        self.actionEqualiser.setObjectName(_fromUtf8("actionEqualiser"))
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setEnabled(False)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setEnabled(False)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.menuActions.addAction(self.play_media_actn)
        self.menuActions.addAction(self.play_cd_actn)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.minimise_tray_actn)
        self.menuActions.addAction(self.prev_track_actn)
        self.menuActions.addAction(self.play_actn)
        self.menuActions.addAction(self.stop_actn)
        self.menuActions.addAction(self.actionNext_Track)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionQuit)
        self.menuPlaylist.addAction(self.actionSave)
        self.menuPlaylist.addSeparator()
        self.menuPlaylist.addAction(self.actionUndo)
        self.menuPlaylist.addAction(self.actionRedo)
        self.menuPlaylist.addSeparator()
        self.menuPlaylist.addAction(self.actionClear)
        self.menuPlaylist.addSeparator()
        self.menuSettings.addAction(self.actionConfigure)
        self.menuHelp.addAction(self.actionAbout_Gereqi)
        self.menuTools.addAction(self.actionUpdate_Collection)
        self.menuTools.addAction(self.actionRescan_Collection)
        self.menuBar.addAction(self.menuActions.menuAction())
        self.menuBar.addAction(self.menuPlaylist.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.search_trktbl_edit)

        self.retranslateUi(MainWindow)
        self.vertical_tabs.setCurrentIndex(1)
        self.horizontal_tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.volume_sldr, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.volume_lbl.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Gereqi", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontal_tabs.setTabText(self.horizontal_tabs.indexOf(self.musicTab), QtGui.QApplication.translate("MainWindow", "Music", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontal_tabs.setTabText(self.horizontal_tabs.indexOf(self.wikipediaTab), QtGui.QApplication.translate("MainWindow", "Wikipedia", None, QtGui.QApplication.UnicodeUTF8))
        self.vertical_tabs.setTabText(self.vertical_tabs.indexOf(self.contentTab), QtGui.QApplication.translate("MainWindow", "Context", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_collect_bttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear Search Field", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_collect_bttn.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.search_collect_edit.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter search terms here", None, QtGui.QApplication.UnicodeUTF8))
        self.search_collect_edit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Enter search terms here", None, QtGui.QApplication.UnicodeUTF8))
        self.collect_time_box.setItemText(0, QtGui.QApplication.translate("MainWindow", "Entire Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.collect_time_box.setItemText(1, QtGui.QApplication.translate("MainWindow", "Added Today", None, QtGui.QApplication.UnicodeUTF8))
        self.collect_time_box.setItemText(2, QtGui.QApplication.translate("MainWindow", "Added Within 1 Week", None, QtGui.QApplication.UnicodeUTF8))
        self.collect_time_box.setItemText(3, QtGui.QApplication.translate("MainWindow", "Added Within 1 Month", None, QtGui.QApplication.UnicodeUTF8))
        self.collect_time_box.setItemText(4, QtGui.QApplication.translate("MainWindow", "Added Within 3 Months", None, QtGui.QApplication.UnicodeUTF8))
        self.collect_time_box.setItemText(5, QtGui.QApplication.translate("MainWindow", "Added Within 1 Year", None, QtGui.QApplication.UnicodeUTF8))
        self.collect_tree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Artist/Album", None, QtGui.QApplication.UnicodeUTF8))
        self.vertical_tabs.setTabText(self.vertical_tabs.indexOf(self.collectionTab), QtGui.QApplication.translate("MainWindow", "Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.rename_playlist_bttn.setText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_playlist_bttn.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.playlist_tree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Playlists", None, QtGui.QApplication.UnicodeUTF8))
        self.vertical_tabs.setTabText(self.vertical_tabs.indexOf(self.playlistsTab), QtGui.QApplication.translate("MainWindow", "Playlists", None, QtGui.QApplication.UnicodeUTF8))
        self.vertical_tabs.setTabText(self.vertical_tabs.indexOf(self.filesTab), QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.connect_dev.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnect_dev.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.vertical_tabs.setTabText(self.vertical_tabs.indexOf(self.devTab), QtGui.QApplication.translate("MainWindow", "Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_trktbl_bttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_trktbl_bttn.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.save_trktbl_bttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Save Playlist As", None, QtGui.QApplication.UnicodeUTF8))
        self.save_trktbl_bttn.setText(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.prev_trktbl_bttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.prev_trktbl_bttn.setText(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.next_trktbl_bttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.next_trktbl_bttn.setText(QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_search_bttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear search field", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_search_bttn.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Search:", None, QtGui.QApplication.UnicodeUTF8))
        self.search_trktbl_edit.setToolTip(QtGui.QApplication.translate("MainWindow", "Playlist Search", None, QtGui.QApplication.UnicodeUTF8))
        self.search_trktbl_edit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Playlist Search", None, QtGui.QApplication.UnicodeUTF8))
        self.track_tbl.setSortingEnabled(True)
        self.prev_bttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Previous Track", None, QtGui.QApplication.UnicodeUTF8))
        self.play_bttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Play/Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_bttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.next_bttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Next Track", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_sldr.setToolTip(QtGui.QApplication.translate("MainWindow", "Volume Control", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_lbl.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.progress_lbl.setText(QtGui.QApplication.translate("MainWindow", "00:00 | 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("MainWindow", "Engage", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlaylist.setTitle(QtGui.QApplication.translate("MainWindow", "Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure.setText(QtGui.QApplication.translate("MainWindow", "Configure Gereqi", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRescan_Collection.setText(QtGui.QApplication.translate("MainWindow", "Rescan Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.play_media_actn.setText(QtGui.QApplication.translate("MainWindow", "Play Media", None, QtGui.QApplication.UnicodeUTF8))
        self.play_media_actn.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.minimise_tray_actn.setText(QtGui.QApplication.translate("MainWindow", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.minimise_tray_actn.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_Collection.setText(QtGui.QApplication.translate("MainWindow", "Update Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Gereqi.setText(QtGui.QApplication.translate("MainWindow", "About  Gereqi", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptTrack.setText(QtGui.QApplication.translate("MainWindow", "Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptAlbum.setText(QtGui.QApplication.translate("MainWindow", "Album", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptPlaylist.setText(QtGui.QApplication.translate("MainWindow", "Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRndOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRndTrack.setText(QtGui.QApplication.translate("MainWindow", "Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRndAlbum.setText(QtGui.QApplication.translate("MainWindow", "Albums", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFavor.setText(QtGui.QApplication.translate("MainWindow", "Favor", None, QtGui.QApplication.UnicodeUTF8))
        self.play_cd_actn.setText(QtGui.QApplication.translate("MainWindow", "Play Audio CD", None, QtGui.QApplication.UnicodeUTF8))
        self.prev_track_actn.setText(QtGui.QApplication.translate("MainWindow", "Previous Track", None, QtGui.QApplication.UnicodeUTF8))
        self.play_actn.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_actn.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Track.setText(QtGui.QApplication.translate("MainWindow", "Next Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEqualiser.setText(QtGui.QApplication.translate("MainWindow", "Equaliser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save Playlist As..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
