# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jon/Documents/Projects/Gereqi/ui/interface.ui'
#
# Created: Thu Feb 18 19:23:17 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 533)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(2)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.parentTabs = QtGui.QTabWidget(self.splitter)
        self.parentTabs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parentTabs.sizePolicy().hasHeightForWidth())
        self.parentTabs.setSizePolicy(sizePolicy)
        self.parentTabs.setMinimumSize(QtCore.QSize(280, 0))
        self.parentTabs.setMaximumSize(QtCore.QSize(480, 16777215))
        self.parentTabs.setTabPosition(QtGui.QTabWidget.West)
        self.parentTabs.setDocumentMode(True)
        self.parentTabs.setObjectName("parentTabs")
        self.contentTab = QtGui.QWidget()
        self.contentTab.setObjectName("contentTab")
        self.gridLayout_2 = QtGui.QGridLayout(self.contentTab)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.contentTabs = QtGui.QTabWidget(self.contentTab)
        self.contentTabs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentTabs.sizePolicy().hasHeightForWidth())
        self.contentTabs.setSizePolicy(sizePolicy)
        self.contentTabs.setMinimumSize(QtCore.QSize(250, 0))
        self.contentTabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.contentTabs.setUsesScrollButtons(False)
        self.contentTabs.setDocumentMode(True)
        self.contentTabs.setTabsClosable(False)
        self.contentTabs.setMovable(False)
        self.contentTabs.setObjectName("contentTabs")
        self.musicTab = QtGui.QWidget()
        self.musicTab.setObjectName("musicTab")
        self.gridLayout_12 = QtGui.QGridLayout(self.musicTab)
        self.gridLayout_12.setMargin(2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.trkNowBox = QtGui.QGroupBox(self.musicTab)
        self.trkNowBox.setStyleSheet("text-decoration: underline;\n"
"font: 75 10pt \"DejaVu Sans\";\n"
"")
        self.trkNowBox.setObjectName("trkNowBox")
        self.gridLayout_8 = QtGui.QGridLayout(self.trkNowBox)
        self.gridLayout_8.setMargin(1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.coverView = QtGui.QLabel(self.trkNowBox)
        self.coverView.setMinimumSize(QtCore.QSize(215, 215))
        self.coverView.setMaximumSize(QtCore.QSize(215, 215))
        self.coverView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.coverView.setFrameShadow(QtGui.QFrame.Raised)
        self.coverView.setPixmap(QtGui.QPixmap(":/Icons/music.png"))
        self.coverView.setAlignment(QtCore.Qt.AlignCenter)
        self.coverView.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.coverView.setObjectName("coverView")
        self.gridLayout_8.addWidget(self.coverView, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.trkNowBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.musicTab)
        self.groupBox_2.setStyleSheet("text-decoration: underline;\n"
"font: 75 10pt \"DejaVu Sans\";\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setMargin(1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.musicTab)
        self.groupBox_3.setStyleSheet("text-decoration: underline;\n"
"font: 75 10pt \"DejaVu Sans\";\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setMargin(1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.musicTab)
        self.groupBox_4.setStyleSheet("text-decoration: underline;\n"
"font: 75 10pt \"DejaVu Sans\";\n"
"")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setMargin(1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.contentTabs.addTab(self.musicTab, "")
        self.lyricsTab = QtGui.QWidget()
        self.lyricsTab.setObjectName("lyricsTab")
        self.gridLayout_5 = QtGui.QGridLayout(self.lyricsTab)
        self.gridLayout_5.setMargin(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lyrcBrowser = QtGui.QTextBrowser(self.lyricsTab)
        self.lyrcBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.lyrcBrowser.setFrameShadow(QtGui.QFrame.Sunken)
        self.lyrcBrowser.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.lyrcBrowser.setOpenLinks(False)
        self.lyrcBrowser.setObjectName("lyrcBrowser")
        self.gridLayout_5.addWidget(self.lyrcBrowser, 0, 0, 1, 1)
        self.contentTabs.addTab(self.lyricsTab, "")
        self.wikipediaTab = QtGui.QWidget()
        self.wikipediaTab.setObjectName("wikipediaTab")
        self.gridLayout_4 = QtGui.QGridLayout(self.wikipediaTab)
        self.gridLayout_4.setMargin(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.wikiView = QtWebKit.QWebView(self.wikipediaTab)
        self.wikiView.setAutoFillBackground(True)
        self.wikiView.setUrl(QtCore.QUrl("about:blank"))
        self.wikiView.setZoomFactor(1.0)
        self.wikiView.setObjectName("wikiView")
        self.gridLayout_4.addWidget(self.wikiView, 0, 0, 1, 1)
        self.contentTabs.addTab(self.wikipediaTab, "")
        self.gridLayout_2.addWidget(self.contentTabs, 0, 1, 1, 1)
        self.parentTabs.addTab(self.contentTab, "")
        self.collectionTab = QtGui.QWidget()
        self.collectionTab.setObjectName("collectionTab")
        self.gridLayout_3 = QtGui.QGridLayout(self.collectionTab)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clrCollectBttn = QtGui.QToolButton(self.collectionTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/edit-clear-locationbar-ltr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clrCollectBttn.setIcon(icon1)
        self.clrCollectBttn.setIconSize(QtCore.QSize(24, 24))
        self.clrCollectBttn.setAutoRaise(True)
        self.clrCollectBttn.setObjectName("clrCollectBttn")
        self.horizontalLayout.addWidget(self.clrCollectBttn)
        self.srchCollectEdt = QtGui.QLineEdit(self.collectionTab)
        self.srchCollectEdt.setObjectName("srchCollectEdt")
        self.horizontalLayout.addWidget(self.srchCollectEdt)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.collectTimeBox = QtGui.QComboBox(self.collectionTab)
        self.collectTimeBox.setMaxVisibleItems(6)
        self.collectTimeBox.setMaxCount(6)
        self.collectTimeBox.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.collectTimeBox.setFrame(True)
        self.collectTimeBox.setObjectName("collectTimeBox")
        self.collectTimeBox.addItem("")
        self.collectTimeBox.addItem("")
        self.collectTimeBox.addItem("")
        self.collectTimeBox.addItem("")
        self.collectTimeBox.addItem("")
        self.collectTimeBox.addItem("")
        self.verticalLayout_2.addWidget(self.collectTimeBox)
        self.collectTree = QtGui.QTreeWidget(self.collectionTab)
        self.collectTree.setAlternatingRowColors(True)
        self.collectTree.setIndentation(15)
        self.collectTree.setRootIsDecorated(True)
        self.collectTree.setAnimated(True)
        self.collectTree.setExpandsOnDoubleClick(False)
        self.collectTree.setObjectName("collectTree")
        self.verticalLayout_2.addWidget(self.collectTree)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.parentTabs.addTab(self.collectionTab, "")
        self.playlistsTab = QtGui.QWidget()
        self.playlistsTab.setObjectName("playlistsTab")
        self.gridLayout_6 = QtGui.QGridLayout(self.playlistsTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addPlylstBttn = QtGui.QToolButton(self.playlistsTab)
        self.addPlylstBttn.setMinimumSize(QtCore.QSize(46, 32))
        self.addPlylstBttn.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.addPlylstBttn.setObjectName("addPlylstBttn")
        self.horizontalLayout_5.addWidget(self.addPlylstBttn)
        self.line_2 = QtGui.QFrame(self.playlistsTab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.rnmPlylstBtnn = QtGui.QToolButton(self.playlistsTab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/edit-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rnmPlylstBtnn.setIcon(icon2)
        self.rnmPlylstBtnn.setIconSize(QtCore.QSize(24, 24))
        self.rnmPlylstBtnn.setAutoRaise(True)
        self.rnmPlylstBtnn.setObjectName("rnmPlylstBtnn")
        self.horizontalLayout_5.addWidget(self.rnmPlylstBtnn)
        self.delPlylstBttn = QtGui.QToolButton(self.playlistsTab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delPlylstBttn.setIcon(icon3)
        self.delPlylstBttn.setIconSize(QtCore.QSize(24, 24))
        self.delPlylstBttn.setAutoRaise(True)
        self.delPlylstBttn.setObjectName("delPlylstBttn")
        self.horizontalLayout_5.addWidget(self.delPlylstBttn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.playlstView = QtGui.QTreeWidget(self.playlistsTab)
        self.playlstView.setObjectName("playlstView")
        self.verticalLayout_5.addWidget(self.playlstView)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.parentTabs.addTab(self.playlistsTab, "")
        self.devicesTab = QtGui.QWidget()
        self.devicesTab.setObjectName("devicesTab")
        self.gridLayout_7 = QtGui.QGridLayout(self.devicesTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.connectDevBttn = QtGui.QPushButton(self.devicesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectDevBttn.sizePolicy().hasHeightForWidth())
        self.connectDevBttn.setSizePolicy(sizePolicy)
        self.connectDevBttn.setMinimumSize(QtCore.QSize(80, 0))
        self.connectDevBttn.setObjectName("connectDevBttn")
        self.horizontalLayout_6.addWidget(self.connectDevBttn)
        self.disconnectDevbttn = QtGui.QPushButton(self.devicesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnectDevbttn.sizePolicy().hasHeightForWidth())
        self.disconnectDevbttn.setSizePolicy(sizePolicy)
        self.disconnectDevbttn.setMinimumSize(QtCore.QSize(80, 0))
        self.disconnectDevbttn.setObjectName("disconnectDevbttn")
        self.horizontalLayout_6.addWidget(self.disconnectDevbttn)
        self.transferDevBttn = QtGui.QComboBox(self.devicesTab)
        self.transferDevBttn.setMinimumSize(QtCore.QSize(80, 0))
        self.transferDevBttn.setObjectName("transferDevBttn")
        self.transferDevBttn.addItem("")
        self.horizontalLayout_6.addWidget(self.transferDevBttn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.devicesComboBox = QtGui.QComboBox(self.devicesTab)
        self.devicesComboBox.setEnabled(False)
        self.devicesComboBox.setObjectName("devicesComboBox")
        self.devicesComboBox.addItem("")
        self.verticalLayout_4.addWidget(self.devicesComboBox)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.clrDevSrch = QtGui.QToolButton(self.devicesTab)
        self.clrDevSrch.setIcon(icon1)
        self.clrDevSrch.setIconSize(QtCore.QSize(24, 24))
        self.clrDevSrch.setAutoRaise(True)
        self.clrDevSrch.setObjectName("clrDevSrch")
        self.horizontalLayout_7.addWidget(self.clrDevSrch)
        self.devSrchEdit = QtGui.QLineEdit(self.devicesTab)
        self.devSrchEdit.setObjectName("devSrchEdit")
        self.horizontalLayout_7.addWidget(self.devSrchEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.deviceTree = QtGui.QTreeWidget(self.devicesTab)
        self.deviceTree.setObjectName("deviceTree")
        self.verticalLayout_6.addWidget(self.deviceTree)
        self.gridLayout_7.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.parentTabs.addTab(self.devicesTab, "")
        self.filesTab = QtGui.QWidget()
        self.filesTab.setObjectName("filesTab")
        self.gridLayout_13 = QtGui.QGridLayout(self.filesTab)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.fileView = QtGui.QTreeView(self.filesTab)
        self.fileView.setIndentation(15)
        self.fileView.setExpandsOnDoubleClick(False)
        self.fileView.setObjectName("fileView")
        self.gridLayout_13.addWidget(self.fileView, 0, 0, 1, 1)
        self.parentTabs.addTab(self.filesTab, "")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clrplyBttn = QtGui.QToolButton(self.layoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/edit-clear-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clrplyBttn.setIcon(icon4)
        self.clrplyBttn.setIconSize(QtCore.QSize(24, 24))
        self.clrplyBttn.setAutoRaise(True)
        self.clrplyBttn.setObjectName("clrplyBttn")
        self.horizontalLayout_4.addWidget(self.clrplyBttn)
        self.svplyBttn = QtGui.QToolButton(self.layoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.svplyBttn.setIcon(icon5)
        self.svplyBttn.setIconSize(QtCore.QSize(24, 24))
        self.svplyBttn.setAutoRaise(True)
        self.svplyBttn.setObjectName("svplyBttn")
        self.horizontalLayout_4.addWidget(self.svplyBttn)
        self.prvplyBttn = QtGui.QToolButton(self.layoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/edit-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prvplyBttn.setIcon(icon6)
        self.prvplyBttn.setIconSize(QtCore.QSize(24, 24))
        self.prvplyBttn.setAutoRaise(True)
        self.prvplyBttn.setObjectName("prvplyBttn")
        self.horizontalLayout_4.addWidget(self.prvplyBttn)
        self.nxtplyBttn = QtGui.QToolButton(self.layoutWidget)
        self.nxtplyBttn.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/edit-redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nxtplyBttn.setIcon(icon7)
        self.nxtplyBttn.setIconSize(QtCore.QSize(24, 24))
        self.nxtplyBttn.setAutoRaise(True)
        self.nxtplyBttn.setObjectName("nxtplyBttn")
        self.horizontalLayout_4.addWidget(self.nxtplyBttn)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.clrsrchBttn = QtGui.QToolButton(self.layoutWidget)
        self.clrsrchBttn.setIcon(icon1)
        self.clrsrchBttn.setIconSize(QtCore.QSize(24, 24))
        self.clrsrchBttn.setAutoRaise(True)
        self.clrsrchBttn.setObjectName("clrsrchBttn")
        self.horizontalLayout_4.addWidget(self.clrsrchBttn)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.srchplyEdit = QtGui.QLineEdit(self.layoutWidget)
        self.srchplyEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.srchplyEdit.setObjectName("srchplyEdit")
        self.horizontalLayout_4.addWidget(self.srchplyEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.playlistTree = QtGui.QTableWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlistTree.sizePolicy().hasHeightForWidth())
        self.playlistTree.setSizePolicy(sizePolicy)
        self.playlistTree.setMinimumSize(QtCore.QSize(400, 0))
        self.playlistTree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.playlistTree.setProperty("showDropIndicator", False)
        self.playlistTree.setDragEnabled(True)
        self.playlistTree.setDragDropOverwriteMode(False)
        self.playlistTree.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.playlistTree.setAlternatingRowColors(True)
        self.playlistTree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.playlistTree.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.playlistTree.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.playlistTree.setShowGrid(False)
        self.playlistTree.setGridStyle(QtCore.Qt.DashLine)
        self.playlistTree.setWordWrap(False)
        self.playlistTree.setCornerButtonEnabled(True)
        self.playlistTree.setObjectName("playlistTree")
        self.playlistTree.setColumnCount(0)
        self.playlistTree.setRowCount(0)
        self.playlistTree.horizontalHeader().setVisible(True)
        self.playlistTree.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.playlistTree)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prevBttn = QtGui.QToolButton(self.layoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/media-skip-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevBttn.setIcon(icon8)
        self.prevBttn.setIconSize(QtCore.QSize(24, 24))
        self.prevBttn.setAutoRaise(True)
        self.prevBttn.setObjectName("prevBttn")
        self.horizontalLayout_3.addWidget(self.prevBttn)
        self.playBttn = QtGui.QToolButton(self.layoutWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBttn.setIcon(icon9)
        self.playBttn.setIconSize(QtCore.QSize(24, 24))
        self.playBttn.setCheckable(True)
        self.playBttn.setAutoRaise(True)
        self.playBttn.setObjectName("playBttn")
        self.horizontalLayout_3.addWidget(self.playBttn)
        self.stopBttn = QtGui.QToolButton(self.layoutWidget)
        self.stopBttn.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/media-playback-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopBttn.setIcon(icon10)
        self.stopBttn.setIconSize(QtCore.QSize(24, 24))
        self.stopBttn.setAutoRaise(True)
        self.stopBttn.setObjectName("stopBttn")
        self.horizontalLayout_3.addWidget(self.stopBttn)
        self.nxtBttn = QtGui.QToolButton(self.layoutWidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/media-skip-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nxtBttn.setIcon(icon11)
        self.nxtBttn.setIconSize(QtCore.QSize(24, 24))
        self.nxtBttn.setAutoRaise(True)
        self.nxtBttn.setObjectName("nxtBttn")
        self.horizontalLayout_3.addWidget(self.nxtBttn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.muteBttn = QtGui.QToolButton(self.layoutWidget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/audio-volume-high.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.muteBttn.setIcon(icon12)
        self.muteBttn.setIconSize(QtCore.QSize(24, 24))
        self.muteBttn.setCheckable(True)
        self.muteBttn.setAutoRaise(True)
        self.muteBttn.setObjectName("muteBttn")
        self.horizontalLayout_3.addWidget(self.muteBttn)
        self.volSldr = QtGui.QSlider(self.layoutWidget)
        self.volSldr.setMaximumSize(QtCore.QSize(200, 200))
        self.volSldr.setMaximum(100)
        self.volSldr.setProperty("value", 100)
        self.volSldr.setOrientation(QtCore.Qt.Horizontal)
        self.volSldr.setInvertedAppearance(False)
        self.volSldr.setInvertedControls(False)
        self.volSldr.setTickPosition(QtGui.QSlider.NoTicks)
        self.volSldr.setObjectName("volSldr")
        self.horizontalLayout_3.addWidget(self.volSldr)
        self.volLbl = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volLbl.sizePolicy().hasHeightForWidth())
        self.volLbl.setSizePolicy(sizePolicy)
        self.volLbl.setMinimumSize(QtCore.QSize(24, 0))
        self.volLbl.setObjectName("volLbl")
        self.horizontalLayout_3.addWidget(self.volLbl)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progSldr = QtGui.QSlider(self.layoutWidget)
        self.progSldr.setMaximum(0)
        self.progSldr.setOrientation(QtCore.Qt.Horizontal)
        self.progSldr.setObjectName("progSldr")
        self.horizontalLayout_2.addWidget(self.progSldr)
        self.progLbl = QtGui.QLabel(self.layoutWidget)
        self.progLbl.setObjectName("progLbl")
        self.horizontalLayout_2.addWidget(self.progLbl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 792, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuActions = QtGui.QMenu(self.menuBar)
        self.menuActions.setObjectName("menuActions")
        self.menuPlaylist = QtGui.QMenu(self.menuBar)
        self.menuPlaylist.setObjectName("menuPlaylist")
        self.menuCurrent = QtGui.QMenu(self.menuPlaylist)
        self.menuCurrent.setObjectName("menuCurrent")
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuSettings = QtGui.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuMode = QtGui.QMenu(self.menuBar)
        self.menuMode.setObjectName("menuMode")
        self.menuRepeat = QtGui.QMenu(self.menuMode)
        self.menuRepeat.setObjectName("menuRepeat")
        self.menuRandom = QtGui.QMenu(self.menuMode)
        self.menuRandom.setObjectName("menuRandom")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionConfigure = QtGui.QAction(MainWindow)
        self.actionConfigure.setObjectName("actionConfigure")
        self.actionRescan_Collection = QtGui.QAction(MainWindow)
        self.actionRescan_Collection.setObjectName("actionRescan_Collection")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPlay_Media = QtGui.QAction(MainWindow)
        self.actionPlay_Media.setObjectName("actionPlay_Media")
        self.actionMinimise_to_Tray = QtGui.QAction(MainWindow)
        self.actionMinimise_to_Tray.setCheckable(True)
        self.actionMinimise_to_Tray.setChecked(True)
        self.actionMinimise_to_Tray.setObjectName("actionMinimise_to_Tray")
        self.actionClear_Current = QtGui.QAction(MainWindow)
        self.actionClear_Current.setObjectName("actionClear_Current")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setIcon(icon4)
        self.actionClear.setObjectName("actionClear")
        self.actionSave_2 = QtGui.QAction(MainWindow)
        self.actionSave_2.setIcon(icon5)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionUpdate_Collection = QtGui.QAction(MainWindow)
        self.actionUpdate_Collection.setObjectName("actionUpdate_Collection")
        self.actionAbout_Gereqi = QtGui.QAction(MainWindow)
        self.actionAbout_Gereqi.setObjectName("actionAbout_Gereqi")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionRptOff = QtGui.QAction(MainWindow)
        self.actionRptOff.setCheckable(True)
        self.actionRptOff.setChecked(True)
        self.actionRptOff.setObjectName("actionRptOff")
        self.actionRptTrack = QtGui.QAction(MainWindow)
        self.actionRptTrack.setCheckable(True)
        self.actionRptTrack.setObjectName("actionRptTrack")
        self.actionRptAlbum = QtGui.QAction(MainWindow)
        self.actionRptAlbum.setCheckable(True)
        self.actionRptAlbum.setObjectName("actionRptAlbum")
        self.actionRptPlaylist = QtGui.QAction(MainWindow)
        self.actionRptPlaylist.setCheckable(True)
        self.actionRptPlaylist.setObjectName("actionRptPlaylist")
        self.actionRndOff = QtGui.QAction(MainWindow)
        self.actionRndOff.setCheckable(True)
        self.actionRndOff.setChecked(True)
        self.actionRndOff.setObjectName("actionRndOff")
        self.actionRndTrack = QtGui.QAction(MainWindow)
        self.actionRndTrack.setCheckable(True)
        self.actionRndTrack.setObjectName("actionRndTrack")
        self.actionRndAlbum = QtGui.QAction(MainWindow)
        self.actionRndAlbum.setCheckable(True)
        self.actionRndAlbum.setObjectName("actionRndAlbum")
        self.actionFavor = QtGui.QAction(MainWindow)
        self.actionFavor.setObjectName("actionFavor")
        self.actionPlay_Audio_CD = QtGui.QAction(MainWindow)
        self.actionPlay_Audio_CD.setObjectName("actionPlay_Audio_CD")
        self.actionPrevious_Track = QtGui.QAction(MainWindow)
        self.actionPrevious_Track.setObjectName("actionPrevious_Track")
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setCheckable(True)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionNext_Track = QtGui.QAction(MainWindow)
        self.actionNext_Track.setObjectName("actionNext_Track")
        self.menuActions.addAction(self.actionPlay_Media)
        self.menuActions.addAction(self.actionPlay_Audio_CD)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionMinimise_to_Tray)
        self.menuActions.addAction(self.actionPrevious_Track)
        self.menuActions.addAction(self.actionPlay)
        self.menuActions.addAction(self.actionStop)
        self.menuActions.addAction(self.actionNext_Track)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionQuit)
        self.menuCurrent.addAction(self.actionClear)
        self.menuCurrent.addAction(self.actionSave_2)
        self.menuCurrent.addAction(self.actionLoad)
        self.menuPlaylist.addAction(self.menuCurrent.menuAction())
        self.menuTools.addAction(self.actionUpdate_Collection)
        self.menuTools.addAction(self.actionRescan_Collection)
        self.menuSettings.addAction(self.actionConfigure)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Gereqi)
        self.menuRepeat.addAction(self.actionRptOff)
        self.menuRepeat.addAction(self.actionRptTrack)
        self.menuRepeat.addAction(self.actionRptAlbum)
        self.menuRepeat.addAction(self.actionRptPlaylist)
        self.menuRandom.addAction(self.actionRndOff)
        self.menuRandom.addAction(self.actionRndTrack)
        self.menuRandom.addAction(self.actionRndAlbum)
        self.menuRandom.addSeparator()
        self.menuRandom.addAction(self.actionFavor)
        self.menuMode.addAction(self.menuRepeat.menuAction())
        self.menuMode.addAction(self.menuRandom.menuAction())
        self.menuBar.addAction(self.menuActions.menuAction())
        self.menuBar.addAction(self.menuPlaylist.menuAction())
        self.menuBar.addAction(self.menuMode.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.srchplyEdit)

        self.retranslateUi(MainWindow)
        self.parentTabs.setCurrentIndex(1)
        self.contentTabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.volSldr, QtCore.SIGNAL("valueChanged(int)"), self.volLbl.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Gereqi", None, QtGui.QApplication.UnicodeUTF8))
        self.trkNowBox.setTitle(QtGui.QApplication.translate("MainWindow", "No Track Playing", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Fresh Podcast Episodes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Your Newest Albums", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Favourite Albums", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.contentTabs.setTabText(self.contentTabs.indexOf(self.musicTab), QtGui.QApplication.translate("MainWindow", "Music", None, QtGui.QApplication.UnicodeUTF8))
        self.contentTabs.setTabText(self.contentTabs.indexOf(self.lyricsTab), QtGui.QApplication.translate("MainWindow", "Lyrics", None, QtGui.QApplication.UnicodeUTF8))
        self.contentTabs.setTabText(self.contentTabs.indexOf(self.wikipediaTab), QtGui.QApplication.translate("MainWindow", "Wikipedia", None, QtGui.QApplication.UnicodeUTF8))
        self.parentTabs.setTabText(self.parentTabs.indexOf(self.contentTab), QtGui.QApplication.translate("MainWindow", "Context", None, QtGui.QApplication.UnicodeUTF8))
        self.clrCollectBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear Search Field", None, QtGui.QApplication.UnicodeUTF8))
        self.clrCollectBttn.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.srchCollectEdt.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter search terms here", None, QtGui.QApplication.UnicodeUTF8))
        self.collectTimeBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Entire Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.collectTimeBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Added Today", None, QtGui.QApplication.UnicodeUTF8))
        self.collectTimeBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Added Within 1 Week", None, QtGui.QApplication.UnicodeUTF8))
        self.collectTimeBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Added Within 1 Month", None, QtGui.QApplication.UnicodeUTF8))
        self.collectTimeBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Added Within 3 Months", None, QtGui.QApplication.UnicodeUTF8))
        self.collectTimeBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Added Within 1 Year", None, QtGui.QApplication.UnicodeUTF8))
        self.collectTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Artist/Album", None, QtGui.QApplication.UnicodeUTF8))
        self.parentTabs.setTabText(self.parentTabs.indexOf(self.collectionTab), QtGui.QApplication.translate("MainWindow", "Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.addPlylstBttn.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.rnmPlylstBtnn.setText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.delPlylstBttn.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.playlstView.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Playlists", None, QtGui.QApplication.UnicodeUTF8))
        self.parentTabs.setTabText(self.parentTabs.indexOf(self.playlistsTab), QtGui.QApplication.translate("MainWindow", "Playlists", None, QtGui.QApplication.UnicodeUTF8))
        self.connectDevBttn.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnectDevbttn.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.transferDevBttn.setItemText(0, QtGui.QApplication.translate("MainWindow", "Transfer", None, QtGui.QApplication.UnicodeUTF8))
        self.devicesComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "No Devices Available", None, QtGui.QApplication.UnicodeUTF8))
        self.clrDevSrch.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Artist/Album", None, QtGui.QApplication.UnicodeUTF8))
        self.parentTabs.setTabText(self.parentTabs.indexOf(self.devicesTab), QtGui.QApplication.translate("MainWindow", "Media Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.parentTabs.setTabText(self.parentTabs.indexOf(self.filesTab), QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.clrplyBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.clrplyBttn.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.svplyBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Save Playlist As", None, QtGui.QApplication.UnicodeUTF8))
        self.svplyBttn.setText(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.prvplyBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.prvplyBttn.setText(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.nxtplyBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.nxtplyBttn.setText(QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.clrsrchBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear search field", None, QtGui.QApplication.UnicodeUTF8))
        self.clrsrchBttn.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Search:", None, QtGui.QApplication.UnicodeUTF8))
        self.srchplyEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Playlist Search", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistTree.setSortingEnabled(True)
        self.prevBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Previous Track", None, QtGui.QApplication.UnicodeUTF8))
        self.playBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Play/Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.nxtBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Next Track", None, QtGui.QApplication.UnicodeUTF8))
        self.volSldr.setToolTip(QtGui.QApplication.translate("MainWindow", "Volume Control", None, QtGui.QApplication.UnicodeUTF8))
        self.volLbl.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.progLbl.setText(QtGui.QApplication.translate("MainWindow", "00:00 | 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("MainWindow", "Engage", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlaylist.setTitle(QtGui.QApplication.translate("MainWindow", "Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCurrent.setTitle(QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMode.setTitle(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRepeat.setTitle(QtGui.QApplication.translate("MainWindow", "Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRandom.setTitle(QtGui.QApplication.translate("MainWindow", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure.setText(QtGui.QApplication.translate("MainWindow", "Configure Gereqi", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRescan_Collection.setText(QtGui.QApplication.translate("MainWindow", "Rescan Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay_Media.setText(QtGui.QApplication.translate("MainWindow", "Play Media", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay_Media.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMinimise_to_Tray.setText(QtGui.QApplication.translate("MainWindow", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMinimise_to_Tray.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Current.setText(QtGui.QApplication.translate("MainWindow", "Clear Current", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_2.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_Collection.setText(QtGui.QApplication.translate("MainWindow", "Update Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Gereqi.setText(QtGui.QApplication.translate("MainWindow", "About  Gereqi", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptTrack.setText(QtGui.QApplication.translate("MainWindow", "Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptAlbum.setText(QtGui.QApplication.translate("MainWindow", "Album", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptPlaylist.setText(QtGui.QApplication.translate("MainWindow", "Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRndOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRndTrack.setText(QtGui.QApplication.translate("MainWindow", "Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRndAlbum.setText(QtGui.QApplication.translate("MainWindow", "Albums", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFavor.setText(QtGui.QApplication.translate("MainWindow", "Favor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay_Audio_CD.setText(QtGui.QApplication.translate("MainWindow", "Play Audio CD", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Track.setText(QtGui.QApplication.translate("MainWindow", "Previous Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Track.setText(QtGui.QApplication.translate("MainWindow", "Next Track", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import resource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

